/* Automatically generated.  Do not edit */
/* See the mkopcodec.awk script for details. */
#if !defined(SQLITE_OMIT_EXPLAIN) || defined(VDBE_PROFILE) || defined(SQLITE_DEBUG)
#if defined(SQLITE_ENABLE_EXPLAIN_COMMENTS) || defined(SQLITE_DEBUG)
# define OpHelp(X) "\0" X
#else
# define OpHelp(X)
#endif
const char *sqlite3OpcodeName(int i){
 static const char *const azName[] = { "?",
     /*   1 */ "Function"         OpHelp("r[P3]=func(r[P2@P5])"),
     /*   2 */ "Savepoint"        OpHelp(""),
     /*   3 */ "AutoCommit"       OpHelp(""),
     /*   4 */ "Transaction"      OpHelp(""),
     /*   5 */ "SorterNext"       OpHelp(""),
     /*   6 */ "PrevIfOpen"       OpHelp(""),
     /*   7 */ "NextIfOpen"       OpHelp(""),
     /*   8 */ "Prev"             OpHelp(""),
     /*   9 */ "Next"             OpHelp(""),
     /*  10 */ "AggStep"          OpHelp("accum=r[P3] step(r[P2@P5])"),
     /*  11 */ "Checkpoint"       OpHelp(""),
     /*  12 */ "JournalMode"      OpHelp(""),
     /*  13 */ "Vacuum"           OpHelp(""),
     /*  14 */ "VFilter"          OpHelp("iPlan=r[P3] zPlan='P4'"),
     /*  15 */ "VUpdate"          OpHelp("data=r[P3@P2]"),
     /*  16 */ "Goto"             OpHelp(""),
     /*  17 */ "Gosub"            OpHelp(""),
     /*  18 */ "Return"           OpHelp(""),
     /*  19 */ "Not"              OpHelp("r[P2]= !r[P1]"),
     /*  20 */ "InitCoroutine"    OpHelp(""),
     /*  21 */ "EndCoroutine"     OpHelp(""),
     /*  22 */ "Yield"            OpHelp(""),
     /*  23 */ "HaltIfNull"       OpHelp("if r[P3]=null halt"),
     /*  24 */ "Halt"             OpHelp(""),
     /*  25 */ "Integer"          OpHelp("r[P2]=P1"),
     /*  26 */ "Int64"            OpHelp("r[P2]=P4"),
     /*  27 */ "String"           OpHelp("r[P2]='P4' (len=P1)"),
     /*  28 */ "Null"             OpHelp("r[P2..P3]=NULL"),
     /*  29 */ "SoftNull"         OpHelp("r[P1]=NULL"),
     /*  30 */ "Blob"             OpHelp("r[P2]=P4 (len=P1)"),
     /*  31 */ "Variable"         OpHelp("r[P2]=parameter(P1,P4)"),
     /*  32 */ "Move"             OpHelp("r[P2@P3]=r[P1@P3]"),
     /*  33 */ "Copy"             OpHelp("r[P2@P3+1]=r[P1@P3+1]"),
     /*  34 */ "SCopy"            OpHelp("r[P2]=r[P1]"),
     /*  35 */ "ResultRow"        OpHelp("output=r[P1@P2]"),
     /*  36 */ "CollSeq"          OpHelp(""),
     /*  37 */ "AddImm"           OpHelp("r[P1]=r[P1]+P2"),
     /*  38 */ "MustBeInt"        OpHelp(""),
     /*  39 */ "RealAffinity"     OpHelp(""),
     /*  40 */ "Permutation"      OpHelp(""),
     /*  41 */ "Compare"          OpHelp(""),
     /*  42 */ "Jump"             OpHelp(""),
     /*  43 */ "Once"             OpHelp(""),
     /*  44 */ "If"               OpHelp(""),
     /*  45 */ "IfNot"            OpHelp(""),
     /*  46 */ "Column"           OpHelp("r[P3]=PX"),
     /*  47 */ "Affinity"         OpHelp("affinity(r[P1@P2])"),
     /*  48 */ "MakeRecord"       OpHelp("r[P3]=mkrec(r[P1@P2])"),
     /*  49 */ "Count"            OpHelp("r[P2]=count()"),
     /*  50 */ "ReadCookie"       OpHelp(""),
     /*  51 */ "SetCookie"        OpHelp(""),
     /*  52 */ "OpenRead"         OpHelp("root=P2 iDb=P3"),
     /*  53 */ "OpenWrite"        OpHelp("root=P2 iDb=P3"),
     /*  54 */ "OpenAutoindex"    OpHelp("nColumn=P2"),
     /*  55 */ "OpenEphemeral"    OpHelp("nColumn=P2"),
     /*  56 */ "SorterOpen"       OpHelp(""),
     /*  57 */ "OpenPseudo"       OpHelp("P3 columns in r[P2]"),
     /*  58 */ "Close"            OpHelp(""),
     /*  59 */ "SeekLT"           OpHelp(""),
     /*  60 */ "SeekLE"           OpHelp(""),
     /*  61 */ "SeekGE"           OpHelp(""),
     /*  62 */ "SeekGT"           OpHelp(""),
     /*  63 */ "Seek"             OpHelp("intkey=r[P2]"),
     /*  64 */ "NoConflict"       OpHelp("key=r[P3@P4]"),
     /*  65 */ "NotFound"         OpHelp("key=r[P3@P4]"),
     /*  66 */ "Found"            OpHelp("key=r[P3@P4]"),
     /*  67 */ "NotExists"        OpHelp("intkey=r[P3]"),
     /*  68 */ "Sequence"         OpHelp("r[P2]=rowid"),
     /*  69 */ "NewRowid"         OpHelp("r[P2]=rowid"),
     /*  70 */ "Insert"           OpHelp("intkey=r[P3] data=r[P2]"),
     /*  71 */ "Or"               OpHelp("r[P3]=(r[P1] || r[P2])"),
     /*  72 */ "And"              OpHelp("r[P3]=(r[P1] && r[P2])"),
     /*  73 */ "InsertInt"        OpHelp("intkey=P3 data=r[P2]"),
     /*  74 */ "Delete"           OpHelp(""),
     /*  75 */ "ResetCount"       OpHelp(""),
     /*  76 */ "IsNull"           OpHelp("if r[P1]==NULL goto P2"),
     /*  77 */ "NotNull"          OpHelp("if r[P1]!=NULL goto P2"),
     /*  78 */ "Ne"               OpHelp("if r[P1]!=r[P3] goto P2"),
     /*  79 */ "Eq"               OpHelp("if r[P1]==r[P3] goto P2"),
     /*  80 */ "Gt"               OpHelp("if r[P1]>r[P3] goto P2"),
     /*  81 */ "Le"               OpHelp("if r[P1]<=r[P3] goto P2"),
     /*  82 */ "Lt"               OpHelp("if r[P1]<r[P3] goto P2"),
     /*  83 */ "Ge"               OpHelp("if r[P1]>=r[P3] goto P2"),
     /*  84 */ "SorterCompare"    OpHelp("if key(P1)!=rtrim(r[P3],P4) goto P2"),
     /*  85 */ "BitAnd"           OpHelp("r[P3]=r[P1]&r[P2]"),
     /*  86 */ "BitOr"            OpHelp("r[P3]=r[P1]|r[P2]"),
     /*  87 */ "ShiftLeft"        OpHelp("r[P3]=r[P2]<<r[P1]"),
     /*  88 */ "ShiftRight"       OpHelp("r[P3]=r[P2]>>r[P1]"),
     /*  89 */ "Add"              OpHelp("r[P3]=r[P1]+r[P2]"),
     /*  90 */ "Subtract"         OpHelp("r[P3]=r[P2]-r[P1]"),
     /*  91 */ "Multiply"         OpHelp("r[P3]=r[P1]*r[P2]"),
     /*  92 */ "Divide"           OpHelp("r[P3]=r[P2]/r[P1]"),
     /*  93 */ "Remainder"        OpHelp("r[P3]=r[P2]%r[P1]"),
     /*  94 */ "Concat"           OpHelp("r[P3]=r[P2]+r[P1]"),
     /*  95 */ "SorterData"       OpHelp("r[P2]=data"),
     /*  96 */ "BitNot"           OpHelp("r[P1]= ~r[P1]"),
     /*  97 */ "String8"          OpHelp("r[P2]='P4'"),
     /*  98 */ "RowKey"           OpHelp("r[P2]=key"),
     /*  99 */ "RowData"          OpHelp("r[P2]=data"),
     /* 100 */ "Rowid"            OpHelp("r[P2]=rowid"),
     /* 101 */ "NullRow"          OpHelp(""),
     /* 102 */ "Last"             OpHelp(""),
     /* 103 */ "SorterSort"       OpHelp(""),
     /* 104 */ "Sort"             OpHelp(""),
     /* 105 */ "Rewind"           OpHelp(""),
     /* 106 */ "SorterInsert"     OpHelp(""),
     /* 107 */ "IdxInsert"        OpHelp("key=r[P2]"),
     /* 108 */ "IdxDelete"        OpHelp("key=r[P2@P3]"),
     /* 109 */ "IdxRowid"         OpHelp("r[P2]=rowid"),
     /* 110 */ "IdxLE"            OpHelp("key=r[P3@P4]"),
     /* 111 */ "IdxGT"            OpHelp("key=r[P3@P4]"),
     /* 112 */ "IdxLT"            OpHelp("key=r[P3@P4]"),
     /* 113 */ "IdxGE"            OpHelp("key=r[P3@P4]"),
     /* 114 */ "Destroy"          OpHelp(""),
     /* 115 */ "Clear"            OpHelp(""),
     /* 116 */ "CreateIndex"      OpHelp("r[P2]=root iDb=P1"),
     /* 117 */ "CreateTable"      OpHelp("r[P2]=root iDb=P1"),
     /* 118 */ "ParseSchema"      OpHelp(""),
     /* 119 */ "LoadAnalysis"     OpHelp(""),
     /* 120 */ "DropTable"        OpHelp(""),
     /* 121 */ "DropIndex"        OpHelp(""),
     /* 122 */ "DropTrigger"      OpHelp(""),
     /* 123 */ "IntegrityCk"      OpHelp(""),
     /* 124 */ "RowSetAdd"        OpHelp("rowset(P1)=r[P2]"),
     /* 125 */ "RowSetRead"       OpHelp("r[P3]=rowset(P1)"),
     /* 126 */ "RowSetTest"       OpHelp("if r[P3] in rowset(P1) goto P2"),
     /* 127 */ "Program"          OpHelp(""),
     /* 128 */ "Param"            OpHelp(""),
     /* 129 */ "FkCounter"        OpHelp("fkctr[P1]+=P2"),
     /* 130 */ "FkIfZero"         OpHelp("if fkctr[P1]==0 goto P2"),
     /* 131 */ "MemMax"           OpHelp("r[P1]=max(r[P1],r[P2])"),
     /* 132 */ "IfPos"            OpHelp("if r[P1]>0 goto P2"),
     /* 133 */ "Real"             OpHelp("r[P2]=P4"),
     /* 134 */ "IfNeg"            OpHelp("if r[P1]<0 goto P2"),
     /* 135 */ "IfZero"           OpHelp("r[P1]+=P3, if r[P1]==0 goto P2"),
     /* 136 */ "AggFinal"         OpHelp("accum=r[P1] N=P2"),
     /* 137 */ "IncrVacuum"       OpHelp(""),
     /* 138 */ "Expire"           OpHelp(""),
     /* 139 */ "TableLock"        OpHelp("iDb=P1 root=P2 write=P3"),
     /* 140 */ "VBegin"           OpHelp(""),
     /* 141 */ "VCreate"          OpHelp(""),
     /* 142 */ "VDestroy"         OpHelp(""),
     /* 143 */ "ToText"           OpHelp(""),
     /* 144 */ "ToBlob"           OpHelp(""),
     /* 145 */ "ToNumeric"        OpHelp(""),
     /* 146 */ "ToInt"            OpHelp(""),
     /* 147 */ "ToReal"           OpHelp(""),
     /* 148 */ "VOpen"            OpHelp(""),
     /* 149 */ "VColumn"          OpHelp("r[P3]=vcolumn(P2)"),
     /* 150 */ "VNext"            OpHelp(""),
     /* 151 */ "VRename"          OpHelp(""),
     /* 152 */ "Pagecount"        OpHelp(""),
     /* 153 */ "MaxPgcnt"         OpHelp(""),
     /* 154 */ "Init"             OpHelp("Start at P2"),
     /* 155 */ "Noop"             OpHelp(""),
     /* 156 */ "Explain"          OpHelp(""),
  };
  return azName[i];
}
#endif
